### ISSUE TITLE
Handling inf & -inf values

### ISSUE THREAD

**Issue by choukha** [equinor/gordo#358]
How to handle inf & -inf values in data ?
+-inf values are not treated as null by default in pandas, https://github.com/pandas-dev/pandas/issues/2858
Ideally inf value should be replaced by a large positive number and -inf should be replaced by negative large number, like we do in dataframe:

df.replace([np.inf, -np.inf],[np.finfo(np.float32).max,np.finfo(np.float32).min])

Choose np.float64 if that's the datatype.

Would be nice to do this using a step in Pipeline or some under the hood pre-processing step like we do fillna during reading.

**Comment by milesgranger** [comment]
I found that using `Imputer(missing_values=[np.inf])` would indeed fill those values; as suspected.
The problem I would **think** will happen, however, is that in yaml
```yaml
sklearn.preprocessing.impute.Imputer:
  missing_values:
    - inf
```
Would result in `inf` being treated as a string. So unless we roll our own "Filler" transformer (which would be pretty damn easy, or even a simple function for `FunctionTransformer`); we would need to modify the serializer, to attempt interpreting parameters at numeric types.

In the meantime, @choukha if you have time to plug an `Imputer` in the pipeline of yours, and see how it goes. You can of course do it locally without needing to run it on the cluster.

**Comment by choukha** [comment]
I tried using     
```
- sklearn.impute.SimpleImputer:
        missing_values: np.inf
        strategy: 'constant'
        fill_value: np.finfo(np.float32).max
```
But this also fails due to some validation checks done by Imputer. ( It checks for finite values before replacing. )
