### ISSUE TITLE
Pass kwargs to keras.Model.compile calls

### ISSUE THREAD

**Issue by milesgranger** [equinor/gordo#366]
When a user entered `keras.Model.compile` specific parameters in their yaml, ie.
```yaml
gordo_components.model.models.SomeKerasModel:
  metrics:
    - mse
```
`metrics` is a parameter to `keras.Model.compile` but it never reaches that method. `kwargs` should also be passed, which can contain arbitrary parameters.
