### ISSUE TITLE
Transform X and y using same scaler when training autoencoders

### ISSUE THREAD

**Issue by Natalie-Caruana** [equinor/gordo#418]
When training an autoencoder, if the features are scaled, we need to scale y in the same way during fitting the model, so that the input to the model is equal to the output.  One way to do so is by using scikit learn TransformedTargetRegressor. This can be implemented in gordo by using the config string
```yaml
sklearn.compose.TransformedTargetRegressor:
    regressor: 
        sklearn.pipeline.Pipeline:
            steps: 
            - sklearn.preprocessing.data.MinMaxScaler
            - gordo_components.model.models.KerasAutoEncoder:
                kind: feedforward_hourglass
                compression_factor: 0.5
                encoding_layers: 2
                func: tanh
                out_func: linear
                epochs: 3
    transformer: sklearn.preprocessing.data.MinMaxScaler
```
By doing so the pipeline becomes an argument to the _TransformedTargetRegressor_, and so the model is no longer a scikit learn pipeline. This breaks parts of the model building, for example the function __get_final_gordo_base_step_ used in _build_model_.
