### ISSUE TITLE
Un-hardcode number of splits for TimeSeriesSplit

### ISSUE THREAD

**Issue by ryanjdillon** [equinor/gordo#800]
In the model builder, the number of splits are currently hard-coded to `3`. This could be set using the `evaluation_config`, so some logic could be added there to allow for this. 

i.e.
```python
 n_splits = evaluation_config["n_splits"] if "n_splits" in evaluation_config else 3
 split_obj = TimeSeriesSplit(n_splits= n_splits)
```

**Comment by milesgranger** [comment]
I would suggest re-using the serializer to load up any `cv` key. so someone would write:

```yaml
evalutation:
  cv:
    sklearn.model_selection.TimeSeriesSplit:
       n_splits: 3
```
